name: Ubuntu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, 'ci osx') && !contains(github.event.head_commit.message, 'ci win')"
    
    runs-on: ubuntu-latest
    
    steps:

      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: ~\.hunter
          key: ${{ runner.os }}-hunter-${{ hashFiles('**/') }}
          restore-keys: |
            ${{ runner.os }}-hunter-

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure
        run: CXXFLAGS="-Wno-error=deprecated-copy" cmake -Bbuild

      - name: Build
        run: cmake --build build -j4

      - name: Test
        run: |
          cd build
          ctest -V --timeout 600

      - name: Build plugin
        run: |
          chmod +x ./scripts/build-plugin.sh
          ./scripts/build-plugin.sh

      - name: create release ${{ github.ref }}
        if: github.ref == 'refs/heads/master'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: upload release asset - libjaegertracing_plugin.so
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ '/home/runner/work/jaeger-client-cpp/jaeger-client-cpp/build/utest/libjaegertracing_plugin.so' }}
          asset_name: ${{ 'libjaegertracing_plugin.so' }}
          asset_content_type: application/zip

