name: Ubuntu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, 'ci osx') && !contains(github.event.head_commit.message, 'ci win')"
    
    runs-on: ubuntu-latest
    
    steps:

      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: ~\.hunter
          key: ${{ runner.os }}-hunter-${{ hashFiles('**/') }}
          restore-keys: |
            ${{ runner.os }}-hunter-

      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "GIT_TAG=$(git describe --tag --always --long | sed -e 's/\(.*\)-\(.*\)-.*/\1.\2/')" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure
        run: CXXFLAGS="-Wno-error=deprecated-copy" cmake -Bbuild

      - name: Build
        run: cmake --build build -j4

      - name: Test
        run: |
          cd build
          ctest -V --timeout 600

      - name: Build plugin
        run: |
          chmod +x ./scripts/build-plugin.sh
          ./scripts/build-plugin.sh

      - name: Release Plug-in
        uses: sondreb/action-release@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "/home/runner/work/jaeger-client-cpp/jaeger-client-cpp/build/utest/libjaegertracing_plugin.so"
          draft: false
          prerelease: false
          name: ${{ format('{0} - {1}', env.GIT_TAG, 'Plugin Release') }}
          tag: ${{ env.GIT_TAG }}
